server:
  port: 8088
#print sql
logging:
  level:
    suitupmonkey:
      system:
        dao: debug

spring:
  #devtools:
    #restart:
      #log-condition-evaluation-delta: false

#  rabbitmq:
#    host: 140.143.67.146
#    port: 5672
#    username: admin
#    password: admin

  profiles:
    avtive: dev

  redis:
    cluster:
      nodes: 140.143.191.219:7002,10.163.4.157:7003,140.143.191.219:7004,140.143.191.219:7005,140.143.191.219:7006,140.143.191.219:7007

  #database config
  datasource:
#    username: root
#    password: 123123
    url: jdbc:mysql://localhost:3306/chatroom?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password:
    driver: com.mysql.jdbc.Driver
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j

mybatis:
  mapper-locations: mybatis/**/*Mapper.xml #mapper location
  typeAliasesPackage: com.suitupmonkey.**.bean #bean alias package
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #print sql


#
#server.port: 443
#server.ssl.key-store: D:\develop\JetBrains\project\chatroom\server.keystore
#server.ssl.key-alias: tomcat
#server.ssl.enabled: true
#server.ssl.key-store-password: 123123
#server.ssl.key-store-type: JKS