#print sql
logging:
  level:
    suitupmonkey:
      system:
        dao: debug

spring:
  #devtools:
    #restart:
      #log-condition-evaluation-delta: false
  profiles:
    avtive: dev

  #database config
  datasource:
    username: root
    password: 123123
    url: jdbc:mysql://localhost:3306/chatroom?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
    driver: com.mysql.cj.jdbc.Driver
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j

mybatis:
  mapper-locations: mybatis/**/*Mapper.xml #mapper location
  typeAliasesPackage: com.suitupmonkey.**.bean #bean alias package
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #print sql

